version: 0.1

phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist jemoji
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Finishing build  ********"
artifacts:
  files:
    - "**/*"
  base-directory: _site/

